// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace LivingArrangementPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("Family?"), LoadColumn(0)]
        public string Family_ { get; set; }


        [ColumnName("Home Zone"), LoadColumn(1)]
        public float Home_Zone { get; set; }


        [ColumnName("Cars"), LoadColumn(2)]
        public float Cars { get; set; }


        [ColumnName("Children"), LoadColumn(3)]
        public float Children { get; set; }


        [ColumnName("Adults"), LoadColumn(4)]
        public float Adults { get; set; }


        [ColumnName("Income"), LoadColumn(5)]
        public float Income { get; set; }


        [ColumnName("Gender"), LoadColumn(6)]
        public float Gender { get; set; }


        [ColumnName("Age"), LoadColumn(7)]
        public float Age { get; set; }


        [ColumnName("Status"), LoadColumn(8)]
        public float Status { get; set; }


        [ColumnName("License"), LoadColumn(9)]
        public float License { get; set; }


        [ColumnName("Distance"), LoadColumn(10)]
        public float Distance { get; set; }


        [ColumnName("Employment"), LoadColumn(11)]
        public float Employment { get; set; }


        [ColumnName("Mode"), LoadColumn(12)]
        public float Mode { get; set; }


    }
}
