// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using LivingArrangement_TTSML.Model;

namespace LivingArrangement_TTSML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\gonza\Desktop\TMG\GitHub\TMG_PORPOS\Data\SMTO_2015_ML_Format.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Family_ with predicted Family_ from sample data...\n\n");
            Console.WriteLine($"Home Zone: {sampleData.Home_Zone}");
            Console.WriteLine($"Cars: {sampleData.Cars}");
            Console.WriteLine($"Children: {sampleData.Children}");
            Console.WriteLine($"Adults: {sampleData.Adults}");
            Console.WriteLine($"Income: {sampleData.Income}");
            Console.WriteLine($"Gender: {sampleData.Gender}");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Status: {sampleData.Status}");
            Console.WriteLine($"License: {sampleData.License}");
            Console.WriteLine($"Distance: {sampleData.Distance}");
            Console.WriteLine($"Employment: {sampleData.Employment}");
            Console.WriteLine($"Mode: {sampleData.Mode}");
            Console.WriteLine($"\n\nActual Family_: {sampleData.Family_} \nPredicted Family_: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
