// This file was auto-generated by ML.NET Model Builder. 

using System;
using LivingArrangementPredictorML.Model;

namespace LivingArrangementPredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Home_Zone = 261F,
                Cars = 1F,
                Children = 3F,
                Adults = 4F,
                Income = 0F,
                Gender = 1F,
                Age = 20F,
                Status = 2F,
                License = 0F,
                Distance = 14F,
                Employment = 0F,
                Mode = 1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Family_ with predicted Family_ from sample data...\n\n");
            Console.WriteLine($"Home_Zone: {sampleData.Home_Zone}");
            Console.WriteLine($"Cars: {sampleData.Cars}");
            Console.WriteLine($"Children: {sampleData.Children}");
            Console.WriteLine($"Adults: {sampleData.Adults}");
            Console.WriteLine($"Income: {sampleData.Income}");
            Console.WriteLine($"Gender: {sampleData.Gender}");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Status: {sampleData.Status}");
            Console.WriteLine($"License: {sampleData.License}");
            Console.WriteLine($"Distance: {sampleData.Distance}");
            Console.WriteLine($"Employment: {sampleData.Employment}");
            Console.WriteLine($"Mode: {sampleData.Mode}");
            Console.WriteLine($"\n\nPredicted Family_ value {predictionResult.Prediction} \nPredicted Family_ scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
